[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-"] }
language-servers = ["pyright"]

